backend/development/urls.py
from django.urls import path

from . import views

app_name = 'development'
urlpatterns = [
    path('detail/<int:pk>', views.DevelopmentDetailView.as_view(), name='detail'),
]

backend/developments/urls.py
from django.urls import path

from . import views

app_name = 'developments'
urlpatterns = [
    path('detail/<int:pk>/', views.DevelopmentDetailView.as_view(), name='detail'),
]

backend/mypage/urls.py
from django.urls import path

from . import views

app_name = 'mypage'
urlpatterns = [
    path('<uuid:pk>/', views.MypageHomeView.as_view(), name='home'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('developments/new/', views.DevelopmentNewView.as_view(), name='developments_new'),
    path('developments/update/<int:pk>/', views.DevelopmentUpdateView.as_view(), name='developments_update'),
    path('developments/delete/<int:pk>/', views.DevelopmentDeleteView.as_view(), name='developments_delete'),
    path('developments/detail/<int:pk>/', views.DevelopmentDetailView.as_view(), name='developments_detail'),
    # path('new_application/', views.NewApplication.as_view(), name='new_application'),
    # path('update_application/<int:id>', views.UpdateApplication.as_view(), name='update_application'),
    # path('delete_application/<int:id>', views.DeleteApplication, name='delete_application'),
    # path('game_detail/<int:pk>/', views.MypageGameDetailView.as_view(), name='game_detail')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .common_settings import *

urlpatterns = [
    path('misw/admin/', admin.site.urls),
    path('', include('social_django.urls')),
    path('', include('backend.oauth.urls')),
    path('', include('backend.home.urls')),
    path('developers/', include('backend.developers.urls')),
    path('', include('backend.developments.urls')),
    path('', include('backend.contact.urls')),
    path('mypage/', include('backend.mypage.urls')),
    path('manage/', include('backend.manage.urls')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

backend/developments/models.py
import os
import re
import mimetypes
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.validators import validate_comma_separated_integer_list

from backend.users.models import User

MEDIA_CHOICES = (
    (0, '画像'),
    (1, '音声'),
    (2, '動画')
)

LINK_CHOICES = (
    (0, 'Microsoft Store'),
    (1, 'Apple Store'),
    (2, 'Google Play'),
    (3, 'Browser'),
    (4, 'Others')
)

ASSOCIATION_CHOICES = (
    (0, 'プログラミング'),
    (1, 'CG'),
    (2, 'MIDI')
)

STATUS_CHOICES = (
    (0, '申請中'),
    (1, '公開中'),
    (2, '非公開')
)

MEDIA_MATCH_PATTERN = {
    'image': '^image/.*$',
    'audio': '^audio/.*$',
    'video': '^video/.*$'
}


def get_media_path(instance, filename):
    root_path = 'developments/medias'
    content = mimetypes.guess_type(filename)[0]

    for key, value in MEDIA_MATCH_PATTERN.items():
        if re.match(value, content):
            return os.path.join(root_path, key, filename)

    return os.path.join(root_path, 'others', filename)


class Media(models.Model):
    id = models.BigAutoField(primary_key=True, editable=False)

    type = models.IntegerField(
        choices=MEDIA_CHOICES,
        help_text='0: image, 1: audio, 2: video'
    )

    file = models.FileField(
        upload_to=get_media_path,
        blank=True,
        null=True
    )

    class Meta:
        verbose_name_plural = 'Media'

    def __str__(self):
        return self.get_type_display()


class Link(models.Model):
    id = models.BigAutoField(primary_key=True, editable=False)

    type = models.IntegerField(
        choices=LINK_CHOICES,
    )

    link = models.URLField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Link'

    def __str__(self):
        return self.get_type_display()


class Development(models.Model):  # ゲーム情報テーブル
    id = models.BigAutoField(primary_key=True, editable=False)

    title = models.CharField(max_length=30)
    description = models.TextField()

    developer = models.ForeignKey(
        User,
        related_name='development_developer',
        on_delete=models.PROTECT
    )
    # 共同開発者
    co_developers = models.ManyToManyField(
        User,
        related_name='development_co_developers',
        blank=True
    )

    associations = models.CharField(
        _('associations'),
        validators=[validate_comma_separated_integer_list],
        max_length=6,
        help_text='0: programming, 1: CG, 2: MIDI',
        blank=True,
        null=True,
        default=''
    )

    status = models.IntegerField(
        _('status'),
        choices=STATUS_CHOICES,
        help_text='0: 申請中, 1: 公開中, 2: 非公開',
        default=0,
    )

    # みす限定公開か否か
    is_private = models.BooleanField(
        default=False,
        help_text='Open only within misw or not'
    )

    top_image = models.ImageField(
        _('top_image'),
        upload_to='developments/images',
        help_text='top image to be listed to home',
        blank=True,
        null=True
    )

    medias = models.ManyToManyField(Media, _('Medias'), blank=True)

    links = models.ManyToManyField(Link, _('links'), blank=True)

    # times
    submitted_at = models.DateTimeField(blank=True, null=True)
    updated_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        verbose_name_plural = 'Development'

    def __str__(self):
        return self.title

    def get_associations(self) -> list:
        associations = self.associations
        if not associations:
            return []
        return associations.split(',')

    def get_associations_display(self) -> str:
        return ', '.join(
            [ASSOCIATION_CHOICES[int(data)][1] for data in self.get_associations()]
        )

backend/development/views.py
from django.views import generic

from backend.models.models import DevelopmentInf


class DevelopmentDetailView(generic.TemplateView):
    template_name = 'development/detail.html'
    model = DevelopmentInf

    def get(self, *args, **kwargs):
        context = {
            'app': DevelopmentInf.objects.get(pk=self.kwargs['pk'], status=1)
        }

        return self.render_to_response(context)

backend/developments/views.py
from django.views import generic

from .models import Development


class DevelopmentDetailView(generic.TemplateView):
    template_name = 'developments/detail.html'
    model = Development

    def get(self, *args, **kwargs):
        context = {
            'development': Development.objects.get(pk=self.kwargs['pk'], status=1)
        }

        return self.render_to_response(context)

backend/mypage/views.py
from django.shortcuts import redirect
from django.utils import timezone
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from backend.developments.models import (
    Development,
    Media,
    Link
)
from backend.users.models import User
from .forms import (
    ProfileUpdateForm,
    DevelopmentCreateForm,
    DevelopmentUpdateForm,
    MediaCreateForm,
    LinkCreateForm
)


class MypageHomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/index.html'
    model = User

    def get(self, *args, **kwargs):
        context = {
            'developments': Development.objects.filter(developer_id=self.kwargs['pk'])
        }
        return self.render_to_response(context)


class ProfileUpdateView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/profile/update.html'

    def get(self, request, *args, **kwargs):
        form = ProfileUpdateForm(
            initial={
                'associations': request.user.get_associations()
            }
        )

        user = self.request.user
        form.fields['generation'].widget.attrs['value'] = user.generation
        form.fields['description'].initial = user.description

        context = dict(form=form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = ProfileUpdateForm(request.POST, request.FILES)
            if form.is_valid():
                user = self.request.user
                cleaned_data = form.cleaned_data
                user.generation = cleaned_data['generation']
                user.associations = ','.join(cleaned_data['associations'])
                user.description = cleaned_data['description']
                if cleaned_data['image']:
                    user.image = cleaned_data['image']
                user.save()

                return redirect('mypage:home', request.user.pk)
        else:
            form = ProfileUpdateForm()

        return redirect('mypage:profile_update')


class DevelopmentNewView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/developments/new.html'

    def get(self, *args, **kwargs):
        development_form = DevelopmentCreateForm()
        media_form = MediaCreateForm()
        link_form = LinkCreateForm()
        development_form.fields['co_developers'].queryset = (
            User.objects.filter(is_superuser=False)
                .exclude(pk=self.request.user.pk)
        )

        context = {
            'development_form': development_form,
            'media_form': media_form,
            'link_form': link_form
        }
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            development_form = DevelopmentCreateForm(request.POST, request.FILES)
            media_form = MediaCreateForm(request.POST, request.FILES)
            link_form = LinkCreateForm(request.POST)

            media_flag = False
            if media_form.is_valid():
                cleaned_data = media_form.cleaned_data
                if cleaned_data['media_type'] and cleaned_data['file']:
                    media_flag = True
                    media = Media()
                    media.type = cleaned_data['media_type']
                    media.file = cleaned_data['file']
                    media.save()

            link_flag = False
            if link_form.is_valid():
                cleaned_data = link_form.cleaned_data
                if cleaned_data['link_type'] and cleaned_data['link']:
                    link_flag = True
                    link = Link()
                    link.type = cleaned_data['link_type']
                    link.link = cleaned_data['link']
                    link.save()

            if development_form.is_valid():
                cleaned_data = development_form.cleaned_data
                development = Development()
                development.title = cleaned_data['title']
                development.description = cleaned_data['description']
                development.developer = request.user
                if cleaned_data['top_image']:
                    development.top_image = cleaned_data['top_image']
                development.associations = ','.join(cleaned_data['associations'])
                development.is_private = cleaned_data['is_private']
                development.save()

                for co_developer in development_form.cleaned_data['co_developers']:
                    development.co_developers.add(co_developer)

                if media_flag:
                    development.medias.add(media)
                if link_flag:
                    development.links.add(link)

                development.submitted_at = timezone.now()
                development.updated_at = timezone.now()
                development.save()

                return redirect('mypage:home', request.user.pk)
        else:
            form = DevelopmentCreateForm

        return redirect('mypage:devlopments_new')


class DevelopmentUpdateView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/developments/update.html'

    def get(self, *args, **kwargs):
        development = Development.objects.get(pk=self.kwargs['pk'])
        media = development.medias.first()
        media_flag = bool(media)
        link = development.links.first()
        link_flag = bool(link)
        development_form_initial = {
            'title': development.title,
            'description': development.description,
            'associations': development.get_associations(),
            'is_private': development.is_private,
            'top_image': [development.top_image if development.top_image else None]
        }
        if media_flag:
            media_form_initial = {
                'media_type': media.type,
                'file': media.file
            }
        else:
            media_form_initial = {}

        if link_flag:
            link_form_initial = {
                'link_type': link.type,
                'link': link.link
            }
        else:
            link_form_initial = {}

        development_form = DevelopmentCreateForm(initial=development_form_initial)
        media_form = MediaCreateForm(initial=media_form_initial)
        link_form = LinkCreateForm(initial=link_form_initial)
        development_form.fields['co_developers'].queryset = (
            User.objects.filter(is_superuser=False)
                .exclude(pk=self.request.user.pk)
        )
        development_form.fields['co_developers'].initial = (
            [co_developer.pk for co_developer in development.co_developers.all()]
        )

        context = {
            'development': development,
            'development_form': development_form,
            'media_form': media_form,
            'link_form': link_form
        }

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        development = Development.objects.get(pk=self.kwargs['pk'])
        media_exists = False
        if development.medias.exists():
            media_exists = True
            media = development.medias.first()
        link_exists = False
        if development.links.exists():
            link = development.links.first()

        if request.method == 'POST':
            development_form = DevelopmentCreateForm(request.POST, request.FILES)
            media_form = MediaCreateForm(request.POST, request.FILES)
            link_form = LinkCreateForm(request.POST)

            media_flag = False
            if media_form.is_valid():
                cleaned_data = media_form.cleaned_data
                if str(cleaned_data['file']) == 'False':
                    media.delete()
                elif cleaned_data['media_type'] and cleaned_data['file']:
                    if not media_exists:
                        media = Media()
                    media_flag = True
                    media.type = cleaned_data['media_type']
                    media.file = cleaned_data['file']
                    media.save()

            link_flag = False
            if link_form.is_valid():
                cleaned_data = link_form.cleaned_data
                if cleaned_data['link_type'] and cleaned_data['link']:
                    if not link_exists:
                        link = Link()
                    link_flag = True
                    link.type = cleaned_data['link_type']
                    link.link = cleaned_data['link']
                    link.save()

            if development_form.is_valid():
                cleaned_data = development_form.cleaned_data
                development.title = cleaned_data['title']
                development.description = cleaned_data['description']
                if str(cleaned_data['top_image']) == 'False':
                    development.top_image.delete()
                elif cleaned_data['top_image']:
                    development.top_image = cleaned_data['top_image']
                development.associations = ','.join(cleaned_data['associations'])
                development.is_private = cleaned_data['is_private']
                development.save()

                development.co_developers.clear()
                for co_developer in development_form.cleaned_data['co_developers']:
                    development.co_developers.add(co_developer)

                if media_flag:
                    development.medias.add(media)
                if link_flag:
                    development.links.add(link)

                development.updated_at = timezone.now()
                development.save()

                return redirect('mypage:home', request.user.pk)
        else:
            form = DevelopmentUpdateForm()

        return redirect('mypage:devlopments_update', development.pk)


class DevelopmentDeleteView(LoginRequiredMixin, generic.TemplateView):

templates/mypage/developments/delete.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  マイページ | 成果物削除
{% endblock title %}

{% block main %}
  <main role="main">
    <div class="container">
      <div class="row">
        <div class="col-12 p-4 text-center text-break">
          <form action="" method="post">
            {% csrf_token %}
            <input type="hidden" value="delete_development">
            <p>本当に削除しますか？</p>
            <button class="btn btn-danger mt-5" type="submit">削除</button>
            <a href="{% url 'mypage:home' user.pk %}" class="btn btn-secondary mt-5 ml-2">キャンセル</a>
          </form>
        </div>
      </div>
    </div>
  </main>
{% endblock main %}

templates/mypage/developments/new.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  マイページ | 新規申請
{% endblock title %}

{% block head %}
  <!-- css link -->
  <link href="{% static 'css/myPage.css' %}" rel="stylesheet">
  <!-- js link -->
  <script type="text/javascript" src="{% static 'js/mypage_application.js' %} "></script>
{% endblock head %}

{% block main %}
  <main role="main">

    <div class="container">
      <h1 class="">新規申請</h1>
      <form id="myform" class="px-4" method="post" enctype="multipart/form-data">
        <!--class="was-validated"-->
        {% csrf_token %}
        <div class="row form-group py-4">
          <label class="col-xs-12 col-sm-4 col-form-label" for="id_title">タイトル</label>
          <div class="col-xs-12 col-sm-8">
            {{ development_form.title }}
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="id_description">説明</label>
          <div class="col-xs-12 col-sm-8">
            {{ development_form.description }}
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label">作成者</label>
          <div class="col-xs-12 col-sm-8">
            <input type="text" id="createdBy" name="createdBy" value="{{ user.first_name }}" disabled></input>
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label">共同作成者</label>
          <div class="col-xs-12 col-sm-8">
            <div id="co_developers_output">
            </div>
            <p>
                <input type="text" id="co_developer_input" placeholder="名前">
                <button type="button" class="btn px-1">
                  <img id="co_developer_add_button" src="{% static 'icons/plus.svg' %}" width="25" alt="共同作成者追加">
                </button>
            </p>
            <p id="co_developer_add_button_assist"></p>
            <div id="developers_area">
              {% for checkbox in development_form.co_developers %}
                <div class="checkbox">
                  <label>
                    {{ checkbox.tag }} 
                    <span id="id_co_developer_name">{{ checkbox.choice_label }}</span>
                  </label>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="is_private">研究会</label>
          <div class="col-xs-12 col-sm-8">
            {% for checkbox in development_form.associations %}
              <div class="checkbox">
                <label for="associations">
                  {{ checkbox.tag }}
                  <span>{{ checkbox.choice_label }}</span>
                </label>
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="id_is_private">みす内のみに公開</label>
          <div class="col-xs-12 col-sm-8">
            {{ development_form.is_private }}
          </div>
        </div>

        <div class="image_input_group row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="id_top_image">トップ画像</label>
          <div class="col-xs-12 col-sm-8">
            {{ development_form.top_image }}
            <div id="new_output_area">
            </div>
          </div>
        </div>

        <hr>
        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="is_private">メディアファイル</label>
          <div class="col-xs-12 col-sm-8"> 
            <!-- media file form is here -->
            <div id="media_file_input_area">
              {% for form in media_forms %}
              <div class="media_file_input py-3">
                <div class="py-1"> 
                  【<span class="media_file_count"></span>】
                  <input type="button" id="remove_media_file_button" class="btn-success float-right" value="-">
                </div>
                <div class="pl-4">
                  {{ form.as_p }} 
                  <div id="new_output_area">
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <div class="pb-4">
              <button type="button" class="btn px-1">
                <img src="{% static 'icons/plus.svg' %}" width="25" alt="メディアファイル追加" id="add_media_file_button">
              </button>
              <span> (max: <span id="media_file_input_num_max"></span>)</span>
            </div>
          </div>
        </div>

        <hr>
        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="is_private">リンク</label>
          <div class="col-xs-12 col-sm-8">
            <!-- link form is here -->
            <div id="link_input_area">
              {% for link in link_forms %}
              <div class="link_input py-3">
                <div class="py-1"> 
                  【<span class="link_count"></span>】
                  <input type="button" id="remove_link_button" class="btn-success float-right " value="-">
                </div>
                <div class="pl-4">
                  {{ link.as_p }} 
                </div>
              </div>
              {% endfor %}
            </div>
            <div class="pb-4">
              <button type="button" class="btn px-1">
                <img src="{% static 'icons/plus.svg' %}" width="25" alt="リンク追加" id="add_link_button">
              </button>
              <span> (max: <span id="link_input_num_max"></span>)</span>
            </div>
          </div>
        </div>

        <hr>
        <div class="p-5">
          <button type="submit" id="submit" class="btn btn-primary pr-4 pl-4 align-content-center">申請</button>
          <!--type="submit"-->
        </div>
      </form>
    </div>
  </main>
{% endblock main %}

templates/mypage/developments/update.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  マイページ | 内容変更申請
{% endblock title %}

{% block head %}
  <!-- css link -->
  <link href="{% static 'css/myPage.css' %}" rel="stylesheet">
  <!-- js link -->
  <script type="text/javascript" src="{% static 'js/mypage_application.js' %} "></script>
{% endblock head %}

{% block main %}
  <main role="main">
    <div class="container">
      <h2 class="">内容変更申請</h2>
      <form id="myform" class="px-4" method="post" enctype="multipart/form-data">
        <!--class="was-validated"-->
        {% csrf_token %}
        {% csrf_token %}
        <div class="row form-group py-4">
          <label class="col-xs-12 col-sm-4 col-form-label" for="id_title">タイトル</label>
          <div class="col-xs-12 col-sm-8">
            {{ development_form.title }}
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="id_description">説明</label>
          <div class="col-xs-12 col-sm-8">
            {{ development_form.description }}
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label">作成者</label>
          <div class="col-xs-12 col-sm-8">
            <input type="text" id="createdBy" name="createdBy" value="{{ user.first_name }}" disabled></input>
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label">共同作成者</label>
          <div class="col-xs-12 col-sm-8">
            <div id="co_developers_output">
            </div>
            <p>
                <input type="text" id="co_developer_input" placeholder="名前">
                <button type="button" class="btn px-1">
                  <img id="co_developer_add_button" src="{% static 'icons/plus.svg' %}" width="25" alt="共同作成者追加">
                </button>
            </p>
            <p id="co_developer_add_button_assist"></p>
            <div id="developers_area">
              {% for checkbox in development_form.co_developers %}
                <div class="checkbox">
                  <label>
                    {{ checkbox.tag }} 
                    <span id="id_co_developer_name">{{ checkbox.choice_label }}</span>
                  </label>
                </div>
              {% endfor %}
            </div>
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="is_private">研究会</label>
          <div class="col-xs-12 col-sm-8">
            {% for checkbox in development_form.associations %}
              <div class="checkbox">
                <label for="associations">
                  {{ checkbox.tag }}
                  <span>{{ checkbox.choice_label }}</span>
                </label>
              </div>
            {% endfor %}
          </div>
        </div>

        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="id_is_private">みす内のみに公開</label>
          <div class="col-xs-12 col-sm-8">
            {{ development_form.is_private }}
          </div>
        </div>

        <div class="image_input_group row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="id_top_image">トップ画像</label>
          <div class="col-xs-12 col-sm-8">
            {% if development.top_image %}
              現在:
              <a href="{{ development.top_image.url }}">{{ development.top_image }}</a>
              <input type="checkbox" name="top_image-clear" id="top_image-clear_id">
              <label for="top_image-clear_id">クリア</label>
              <div id="old_output_area">
                <img src="{{ development.top_image.url }}" class="top_image "></img>
              </div>
              <br>
              変更:
            {% endif %}
            {{ development_form.top_image }}
            <div id="new_output_area" class="top_image">
            </div>
          </div>
        </div>

        <hr>
        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="is_private">メディアファイル</label>
          <div class="col-xs-12 col-sm-8"> 
            <!-- media file form is here -->
            <div id="media_file_input_area">
              {% for form in media_forms %}
              <div class="media_file_input py-3">
                <div class="py-1"> 
                  【<span class="media_file_count"></span>】
                  <input type="button" id="remove_media_file_button" class="btn-success float-right" value="-">
                </div>
                <div class="pl-4">
                  {{ form.as_p }} 
                  <div id="new_output_area">
                  </div>
                </div>
              </div>
              {% endfor %}
            </div>
            <div class="pb-4">
              <button type="button" class="btn px-1">
                <img src="{% static 'icons/plus.svg' %}" width="25" alt="メディアファイル追加" id="add_media_file_button">
              </button>
              <span> (max: <span id="media_file_input_num_max"></span>)</span>
            </div>
          </div>
        </div>

        <hr>
        <div class="row form-group py-3">
          <label class="col-xs-12 col-sm-4 col-form-label" for="is_private">リンク</label>
          <div class="col-xs-12 col-sm-8">
            <!-- link form is here -->
            <div id="link_input_area">
              {% for link in link_forms %}
              <div class="link_input py-3">
                <div class="py-1"> 
                  【<span class="link_count"></span>】
                  <input type="button" id="remove_link_button" class="btn-success float-right " value="-">
                </div>
                <div class="pl-4">
                  {{ link.as_p }} 
                </div>
              </div>
              {% endfor %}
            </div>
            <div class="pb-4">
              <button type="button" class="btn px-1">
                <img src="{% static 'icons/plus.svg' %}" width="25" alt="リンク追加" id="add_link_button">
              </button>
              <span> (max: <span id="link_input_num_max"></span>)</span>
            </div>
          </div>
        </div>

        <hr>
        <div class="col-12 text-center text-break">
          <a class="pr-3">
            <button type="submit" class="btn btn-primary">変更申請</button>
          </a>
          <a href="{% url 'mypage:developments_delete' development.pk %}" class="btn btn-danger" id="form_delete">削除</a>
          <span class="pl-4">
            <a href="{% url 'mypage:home' user.pk %}" class="btn btn-secondary">戻る</a>
          </span>
        </div>
      </form>
    </div>
  </main>
{% endblock main %}