backend/mypage/urls.py
from django.urls import path

from . import views

app_name = 'mypage'
urlpatterns = [
    path('<uuid:pk>/', views.MypageHomeView.as_view(), name='home'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('developments/new/', views.DevelopmentNewView.as_view(), name='developments_new'),
    path('developments/update/<int:pk>/', views.DevelopmentUpdateView.as_view(), name='developments_update'),
    path('developments/delete/<int:pk>/', views.DevelopmentDeleteView.as_view(), name='developments_delete'),
    path('developments/detail/<int:pk>/', views.DevelopmentDetailView.as_view(), name='developments_detail'),
    # path('new_application/', views.NewApplication.as_view(), name='new_application'),
    # path('update_application/<int:id>', views.UpdateApplication.as_view(), name='update_application'),
    # path('delete_application/<int:id>', views.DeleteApplication, name='delete_application'),
    # path('game_detail/<int:pk>/', views.MypageGameDetailView.as_view(), name='game_detail')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .common_settings import *

urlpatterns = [
    path('misw/admin/', admin.site.urls),
    path('', include('social_django.urls')),
    path('', include('backend.oauth.urls')),
    path('', include('backend.home.urls')),
    path('developers/', include('backend.developers.urls')),
    path('', include('backend.developments.urls')),
    path('', include('backend.contact.urls')),
    path('mypage/', include('backend.mypage.urls')),
    path('manage/', include('backend.manage.urls')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

backend/mypage/forms.py
from django import forms

from backend.developments.models import (
    Development,
    Media,
    Link,
    ASSOCIATION_CHOICES,
    MEDIA_CHOICES,
    LINK_CHOICES
)
from backend.users.models import User


class ProfileUpdateForm(forms.ModelForm):
    generation = forms.IntegerField(required=False, max_value=999, min_value=0)
    associations = forms.MultipleChoiceField(
        choices=ASSOCIATION_CHOICES,
        required=False,
        widget=forms.CheckboxSelectMultiple
    )
    description = forms.CharField(required=False, widget=forms.Textarea)
    image = forms.FileField(required=False)

    class Meta:
        model = User
        fields = (
            'generation',
            'description',
            'image'
        )


class DevelopmentCreateForm(forms.ModelForm):
    title = forms.CharField(required=True, max_length=30)
    description = forms.CharField(required=False, widget=forms.Textarea)
    co_developers = forms.ModelMultipleChoiceField(
        queryset=User.objects.all(),
        required=False,
        widget=forms.CheckboxSelectMultiple
    )
    associations = forms.MultipleChoiceField(
        choices=ASSOCIATION_CHOICES,
        required=False,
        widget=forms.CheckboxSelectMultiple
    )
    top_image = forms.FileField(required=False)
    is_private = forms.BooleanField(required=False)

    class Meta:
        model = Development
        fields = (
            'title',
            'description',
            'top_image',
            'is_private'
        )


class MediaCreateForm(forms.ModelForm):
    MEDIA_CHOICES_WITH_EMPTY = [(None, '----')] + list(MEDIA_CHOICES)

    # link form とのid衝突回避のため
    media_type = forms.ChoiceField(choices=MEDIA_CHOICES_WITH_EMPTY, label='type', required=False)
    file = forms.FileField(required=False)

    class Meta:
        model = Media
        fields = (
            'media_type',
            'file'
        )


class LinkCreateForm(forms.ModelForm):
    LINK_CHOICES_WITH_EMPTY = [(None, '----')] + list(LINK_CHOICES)

    # media form とのid衝突回避のため
    link_type = forms.ChoiceField(choices=LINK_CHOICES_WITH_EMPTY, label='type', required=False)
    link = forms.URLField(required=False)

    class Meta:
        model = Link
        fields = (
            'link_type',
            'link'
        )


class DevelopmentUpdateForm(DevelopmentCreateForm):
    title = forms.CharField(required=False, max_length=30)

    class Meta:
        model = Development
        fields = (
            'title',
            'description',
            'top_image',
            'is_private'
        )

backend/mypage/views.py
from django.shortcuts import redirect
from django.utils import timezone
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin

from backend.developments.models import (
    Development,
    Media,
    Link
)
from backend.users.models import User
from .forms import (
    ProfileUpdateForm,
    DevelopmentCreateForm,
    DevelopmentUpdateForm,
    MediaCreateForm,
    LinkCreateForm
)


class MypageHomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/index.html'
    model = User

    def get(self, *args, **kwargs):
        context = {
            'developments': Development.objects.filter(developer_id=self.kwargs['pk'])
        }
        return self.render_to_response(context)


class ProfileUpdateView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/profile/update.html'

    def get(self, request, *args, **kwargs):
        form = ProfileUpdateForm(
            initial={
                'associations': request.user.get_associations()
            }
        )

        user = self.request.user
        form.fields['generation'].widget.attrs['value'] = user.generation
        form.fields['description'].initial = user.description

        context = dict(form=form)
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = ProfileUpdateForm(request.POST, request.FILES)
            if form.is_valid():
                user = self.request.user
                cleaned_data = form.cleaned_data
                user.generation = cleaned_data['generation']
                user.associations = ','.join(cleaned_data['associations'])
                user.description = cleaned_data['description']
                if cleaned_data['image']:
                    user.image = cleaned_data['image']
                user.save()

                return redirect('mypage:home', request.user.pk)
        else:
            form = ProfileUpdateForm()

        return redirect('mypage:profile_update')


class DevelopmentNewView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/developments/new.html'

    def get(self, *args, **kwargs):
        development_form = DevelopmentCreateForm()
        media_form = MediaCreateForm()
        link_form = LinkCreateForm()
        development_form.fields['co_developers'].queryset = (
            User.objects.filter(is_superuser=False)
                .exclude(pk=self.request.user.pk)
        )

        context = {
            'development_form': development_form,
            'media_form': media_form,
            'link_form': link_form
        }
        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            development_form = DevelopmentCreateForm(request.POST, request.FILES)
            media_form = MediaCreateForm(request.POST, request.FILES)
            link_form = LinkCreateForm(request.POST)

            media_flag = False
            if media_form.is_valid():
                cleaned_data = media_form.cleaned_data
                if cleaned_data['media_type'] and cleaned_data['file']:
                    media_flag = True
                    media = Media()
                    media.type = cleaned_data['media_type']
                    media.file = cleaned_data['file']
                    media.save()

            link_flag = False
            if link_form.is_valid():
                cleaned_data = link_form.cleaned_data
                if cleaned_data['link_type'] and cleaned_data['link']:
                    link_flag = True
                    link = Link()
                    link.type = cleaned_data['link_type']
                    link.link = cleaned_data['link']
                    link.save()

            if development_form.is_valid():
                cleaned_data = development_form.cleaned_data
                development = Development()
                development.title = cleaned_data['title']
                development.description = cleaned_data['description']
                development.developer = request.user
                if cleaned_data['top_image']:
                    development.top_image = cleaned_data['top_image']
                development.associations = ','.join(cleaned_data['associations'])
                development.is_private = cleaned_data['is_private']
                development.save()

                for co_developer in development_form.cleaned_data['co_developers']:
                    development.co_developers.add(co_developer)

                if media_flag:
                    development.medias.add(media)
                if link_flag:
                    development.links.add(link)

                development.submitted_at = timezone.now()
                development.updated_at = timezone.now()
                development.save()

                return redirect('mypage:home', request.user.pk)
        else:
            form = DevelopmentCreateForm

        return redirect('mypage:devlopments_new')


class DevelopmentUpdateView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'mypage/developments/update.html'

    def get(self, *args, **kwargs):
        development = Development.objects.get(pk=self.kwargs['pk'])
        media = development.medias.first()
        media_flag = bool(media)
        link = development.links.first()
        link_flag = bool(link)
        development_form_initial = {
            'title': development.title,
            'description': development.description,
            'associations': development.get_associations(),
            'is_private': development.is_private,
            'top_image': [development.top_image if development.top_image else None]
        }
        if media_flag:
            media_form_initial = {
                'media_type': media.type,
                'file': media.file
            }
        else:
            media_form_initial = {}

        if link_flag:
            link_form_initial = {
                'link_type': link.type,
                'link': link.link
            }
        else:
            link_form_initial = {}

        development_form = DevelopmentCreateForm(initial=development_form_initial)
        media_form = MediaCreateForm(initial=media_form_initial)
        link_form = LinkCreateForm(initial=link_form_initial)
        development_form.fields['co_developers'].queryset = (
            User.objects.filter(is_superuser=False)
                .exclude(pk=self.request.user.pk)
        )
        development_form.fields['co_developers'].initial = (
            [co_developer.pk for co_developer in development.co_developers.all()]
        )

        context = {
            'development': development,
            'development_form': development_form,
            'media_form': media_form,
            'link_form': link_form
        }

        return self.render_to_response(context)

    def post(self, request, *args, **kwargs):
        development = Development.objects.get(pk=self.kwargs['pk'])
        media_exists = False
        if development.medias.exists():
            media_exists = True
            media = development.medias.first()
        link_exists = False
        if development.links.exists():
            link = development.links.first()

        if request.method == 'POST':
            development_form = DevelopmentCreateForm(request.POST, request.FILES)
            media_form = MediaCreateForm(request.POST, request.FILES)
            link_form = LinkCreateForm(request.POST)

            media_flag = False
            if media_form.is_valid():
                cleaned_data = media_form.cleaned_data
                if str(cleaned_data['file']) == 'False':
                    media.delete()
                elif cleaned_data['media_type'] and cleaned_data['file']:
                    if not media_exists:
                        media = Media()
                    media_flag = True
                    media.type = cleaned_data['media_type']
                    media.file = cleaned_data['file']
                    media.save()

            link_flag = False
            if link_form.is_valid():
                cleaned_data = link_form.cleaned_data
                if cleaned_data['link_type'] and cleaned_data['link']:
                    if not link_exists:
                        link = Link()
                    link_flag = True
                    link.type = cleaned_data['link_type']
                    link.link = cleaned_data['link']
                    link.save()

            if development_form.is_valid():
                cleaned_data = development_form.cleaned_data
                development.title = cleaned_data['title']
                development.description = cleaned_data['description']
                if str(cleaned_data['top_image']) == 'False':
                    development.top_image.delete()
                elif cleaned_data['top_image']:
                    development.top_image = cleaned_data['top_image']
                development.associations = ','.join(cleaned_data['associations'])
                development.is_private = cleaned_data['is_private']
                development.save()

                development.co_developers.clear()
                for co_developer in development_form.cleaned_data['co_developers']:
                    development.co_developers.add(co_developer)

                if media_flag:
                    development.medias.add(media)
                if link_flag:
                    development.links.add(link)

                development.updated_at = timezone.now()
                development.save()

                return redirect('mypage:home', request.user.pk)
        else:
            form = DevelopmentUpdateForm()

        return redirect('mypage:devlopments_update', development.pk)


class DevelopmentDeleteView(LoginRequiredMixin, generic.TemplateView):

templates/mypage/change.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  マイページ | プロフィール変更
{% endblock title %}

{% block head %}
  <!-- css link -->
  <link href="{% static 'css/myPage.css' %}" rel="stylesheet">
  <!-- js link -->
  <script type="text/javascript" src="{% static 'js/mypage_profile.js' %}"></script>
{% endblock head %}

{% block main %}
  <main role="main">
    <form action="{% url 'mypage:update_profile' %}" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <!-- profile  -->
      <section class="p-5" style="background-color: rgb(238, 237, 237);">
        <div class="container">
          <div class="row align-items-center mx-auto justify-content-center">
            <div class="col-12 col-md-4 text-center pb-5">
              <!-- col-12 col-md-4 -->
              <!-- col-4 col-auto-->

              <label for="profileImageInput">
                {% if user.user_image %}
                  <img class="rounded-circle" src="{{ user.user_image.url }}" width="200" height="200">
                {% else %}
                  <img class="rounded-circle" src="{% static 'icons/profile.svg' %}" width="200" height="200">
                {% endif %}
              </label>
              <input id="profileImageInput" name="profileImageInput" type="file" class="form-control-file center-block"
                     name="profileImageInput" accept="image/*">

            </div>
            <div class="col-12 col-md-8 text-left ">
              <!-- col-12 col-md-8 -->
              <!-- col-8 col-auto-->
              <div style="overflow-wrap: break-word; word-wrap: break-word;"></div>
              <div class="row form-group">
                <span class="col-6 col-md-5">ハンドルネーム: </span>
                <span class="col-6 col-md-5">{{ user.first_name }}</span>
              </div>
              <div class="row form-group">
                <p class="col-6 col-md-5">
                  <label for="generationInput">代: </label>
                </p>
                <p class="col-6 col-md-5">
                  <input type="number" id="generationInput" name="generationInput" min="0" max="300"
                         value="{{ user.generation }}">
                </p>
              </div>
              <div class="row form-group">
                <p class="col-6 col-md-5">
                  <label for="shortCommentInput">ひとこと: </label>
                </p>
                <textarea class="col-6 col-md-5" id="shortCommentInput" name="shortCommentInput" rows="5"
                          placeholder="自己紹介など">{{ description }}</textarea>
              </div>
            </div>
          </div>

        </div>
        </div>
      </section>

      <div class="text-center p-5">
        <button id="changeButton" type="submit" class="btn btn-primary pr-3 pl-3 m-3">変更保存</button>
        <a href="{% url 'mypage:mypage_home' %}">
          <button type="button" class="btn btn-outline-danger pr-3 pl-3 m-3">戻る</button>
        </a>
      </div>

    </form>

  </main>
{% endblock main %}

templates/mypage/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  マイページ
{% endblock title %}

{% block head %}
  <!-- css link -->
  <link href="{% static 'css/myPage.css' %}" rel="stylesheet">
{% endblock head %}

{% block main %}
  <main role="main">
    <!-- profile  -->
    <section class="p-5" style="background-color: rgb(238, 237, 237);">
      <div class="container">
        <div class="row align-items-center mx-auto justify-content-center">
          <div class="col-12 col-md-4 text-center">
            <!-- col-12 col-md-4 -->
            <!-- col-4 col-auto-->

            {% if user.image %}
              <img class="rounded-circle" src="{{ user.image.url }}" width="200" height="200">
            {% else %}
              <img class="rounded-circle" src="{% static 'icons/profile.svg' %}" width="200" height="200">
            {% endif %}
          </div>
          <div class="d-md-none p-4"></div>
          <div class="col-12 col-md-8 text-left">
            <!-- col-12 col-md-8 -->
            <!-- col-8 col-auto-->
            <div style="overflow-wrap: break-word; word-wrap: break-word;">
              <div class="row p-2">
                <span class="col-6 col-md-5">ユーザーネーム: </span>
                <span class="col-6 col-md-5">{{ user.username }}</span>
              </div>
              <div class="row p-2">
                <span class="col-6 col-md-5">ハンドルネーム: </span>
                <span class="col-6 col-md-5">{{ user.first_name }}</span>
              </div>
              <div class="row p-2">
                <span class="col-6 col-md-5">代: </span>
                {% if user.generation %}
                  <span class="col-6 col-md-5">{{ user.generation }}</span>
                {% else %}
                  <span class="col-6 col-md-5">-</span>
                {% endif %}
              </div>
              <div class="row p-2">
                <span class="col-6 col-md-5">研究会: </span>
                {% if user.get_associations_display %}
                  <span class="col-6 col-md-5">{{ user.get_associations_display }}</span>
                {% else %}
                  <span class="col-6 col-md-5">-</span>
                {% endif %}
              </div>
              <div class="row p-2">
                <span class="col-12 col-md-5">ひとこと: </span>
                <span class="col-12 col-md-5">
                <p>{{ user.description | linebreaksbr }}</p>
              </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div class="container ">
      <!-- 作成したゲーム一覧 -->
      <div class="row justify-content-center">

        <div class="p-4 col-12">
          <!-- 個人作成ゲーム -->
          <p class="h2">個人作成</p>
          <table class="table  table-hover p-2 text-nowrap overflow-auto ">
            <!--table-responsive-->
            <thead class="thead-light">
            <tr>
              <th class="d-table-cell" style="width:15%;">状態</th>
              <th class="d-none d-md-table-cell" style="width:15%;">ID</th>
              <th class="d-none d-md-table-cell" style="width:10%;">トップ画像</th>
              <th class="d-table-cell" style="width:20%;">タイトル</th>
              <th class="d-none d-md-table-cell" style="width:15%;"></th>
              <th class="d-table-cell" style="width:15%;"></th>
            </tr>
            </thead>
            <tbody>
            {% for development in developments %}
              <tr>
                <td class="d-table-cell">
                  {% if development.status == 1 %}
                    <span class="btn btn-primary status_public">公開</span>
                  {% elif development.status == 2 %}
                    <span class="btn btn-success btn-sm">非公開</span>
                  {% else %}
                    <span class="btn btn-info btn-sm">申請中</span>
                  {% endif %}
                <td class="d-none d-md-table-cell align-middle">{{ development.id }}</td>
                {% if development.top_image %}
                  <td class="d-none d-md-table-cell align-middle">
                    <img src="{{ development.top_image.url }}" width="32" height="32">
                  </td>
                {% else %}
                  <td class="d-none d-md-table-cell align-middle">
                    <img src="{% static 'icons/noimage.png' %}" width="32" height="32">
                  </td>
                {% endif %}

                <td class="d-table-cell  text-wrap align-middle">{{ development.title }}</td>
                <!--overflow-hidden  -->
                <td class="d-none d-md-table-cell align-middle"></td>
                <td class="d-table-cell align-middle">
                  <a href="{% url 'mypage:developments_detail' development.pk %}">
                    <button class="btn btn-outline-dark">詳細</button>
                  </a>
                  <a href="{% url 'mypage:developments_update' development.pk %}">
                    <button class="btn btn-success">変更</button>
                  </a>
                </td>
              </tr>
            {% endfor %}

            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>
{% endblock main %}

templates/mypage/mypage_application_change.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
マイページ | 内容変更申請
{% endblock title %}

{% block head %}
<!-- css link -->
<link href="{% static 'css/myPage.css' %}" rel="stylesheet">
<!-- js link -->
<script type="text/javascript" src="{% static 'js/mypage_application.js' %} "></script>
{% endblock head %}

{% block main %}
<main role="main">

  <!--基本情報-->
  <!--
  <div class="row" >
      <p class="col-md-3">状態：　<span>公開中</span></p>
      <p class="col-md-3">ゲームID:　<span>0000000</span> </p>
  </div>
  -->


  <div class="container">
    <h2 class="">内容変更申請</h2>
    <form id="myform" class="px-4"  action="{% url 'mypage:update_application' app.id%}" method="post" enctype="multipart/form-data">
      <!--class="was-validated"-->
      {% csrf_token %}
      <div class="row form-group py-4">
        <label class="col-xs-12 col-sm-5 col-form-label" for="gameTitle">ゲームタイトル</label>
        <div class="col-xs-12 col-sm-7">
          <input class="form-control" id="gameTitle" name="gameTitle" type="text" placeholder="入力" value="{{ app.title }}" required>
        </div>
      </div>


      <div class="row form-group py-3">
        <label class="col-xs-12 col-sm-5 col-form-label" for="introduction">ゲームの説明</label>
        <div class="col-xs-12 col-sm-7">
          <textarea class="form-control" id="introduction" name="introduction" rows="5" required>{{ app.description }}</textarea>
        </div>
      </div>

      <div class="row form-group py-3">
        <label class="col-xs-12 col-sm-5 col-form-label">作成者</label>
        <div class="col-xs-12 col-sm-7">
          <input type="text" id="createdBy" name="createdBy" value="{{user.first_name}}" disabled></input>
          <p class="" data-toggle="collapse" href="#developer_div" aria-expanded="false" aria-controls="developer_div">
            <img src="{% static 'icons/plus.svg' %}" width="25" alt="作成者追加">
            <span id="co_createdBy" class="bg-white pt-1 pb-1"></span>
          </p>
          <div class="collapse bg-light" id="developer_div">
            <p>申請者(あなた)以外の作成者:</p>
            <input type="checkbox" name="developer" id=""><label for="">name1</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name2</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name3</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name4</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name5</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name6_</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name7__</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name8</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">nam9</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name10_</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name11_</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">n12</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">na13</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">n14</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">n15</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">16</label><span>　</span>
            <input type="checkbox" name="developer" id=""><label for="">name17_</label><span>　</span>

          </div>
        </div>
      </div>

      <div class="row form-group py-3">
        <label class="col-xs-12 col-sm-5 col-form-label">ゲームカテゴリ</label>
        <div class="col-xs-12 col-sm-7">
          <select id="gameCategory" name="gameCategory" class="form-control" required>
            <option disabled selected value>選んでください</option>
            <option {% if app.categoryname == "RPG" %}selected{% endif %}>RPG</option>
            <option {% if app.categoryname == "アクション" %}selected{% endif %}>アクション</option>
            <option {% if app.categoryname == "シューティング" %}selected{% endif %}>シューティング</option>
            <option {% if app.categoryname == "パズル" %}selected{% endif %}>パズル</option>
            <option {% if app.categoryname == "音ゲー" %}selected{% endif %}>音ゲー</option>
            <option {% if app.categoryname == "その他" %}selected{% endif %}>その他</option>
          </select>
        </div>
      </div>

      <div class="row form-group py-3">
        <div class="col-xs-12 col-sm-7">
          <input type="file" name="gameImage" accept="image/*" class="img-fluid" id="gameImage" alt="画像を追加してください">
          <label class="bor" for="gameImageInput">
            {% if app.image %}
              <img src="{{app.image.url}}" width="25" alt="画像追加">
            {% else %}
              <img src="{% static 'icons/plus.svg' %}" width="25" alt="画像追加">
            {% endif %}

          </label>

        </div>

      </div>

      <div class="row form-group py-3">
        <div class="col-xs-12 col-sm-5">
          <label class="col-form-label">対応機種</label>
        </div>
        <div class="col-xs-12 col-sm-7">
          <div>
            <input class="form-check-input" type="checkbox" id="check0" name="check0" data-toggle="collapse"
              data-target="#link0" href="#link0" aria-expanded="false" aria-controls="link0" value="" {% if app.link_browser%}checked{%endif%}>
            <label class="form-check-label" for="check0">ブラウザ</label>
            <div class="collapse {% if app.link_browser%}show{%endif%}" id="link0">
              <input type="url" class="col-xs-12" name="link_browser" placeholder="ダウンロードリンク" value="{% if app.link_browser != None %}{{app.link_browser}}{%endif%}">
            </div>
          </div>
          <div>
            <input class="form-check-input" type="checkbox" id="check1" name="check1" data-toggle="collapse"
              data-target="#link1" href="#link1" aria-expanded="false" aria-controls="link1" {% if app.link_Windows%}checked{%endif%}>
            <label class="form-check-label" for="check1">Windows</label>
            <div class="collapse {% if app.link_Windows%}show{%endif%}" id="link1">
              <input type="url" class="col-xs-12" name="link_Windows" placeholder="ダウンロードリンク" value="{% if app.link_Windows != None %}{{app.link_Windows}}{%endif%}">
            </div>
          </div>
          <div>
            <input class="form-check-input" type="checkbox" id="check2" name="check2" data-toggle="collapse"
              data-target="#link2" href="#link2" aria-expanded="false" aria-controls="link2" {% if app.link_Mac%}checked{%endif%}>
            <label class="form-check-label" for="check2">Mac</label>
            <div class="collapse {% if app.link_Mac%}show{%endif%}" id="link2">
              <input type="url" class="col-xs-12" name="link_Mac" placeholder="ダウンロードリンク" value="{% if app.link_Mac  != None %}{{app.link_Mac}}{%endif%}">
            </div>
          </div>
          <div>
            <input class="form-check-input" type="checkbox" id="check3" name="check3" data-toggle="collapse"
              data-target="#link3" href="#link3" aria-expanded="false" aria-controls="link3" {% if app.link_Android%}checked{%endif%}>
            <label class="form-check-label" for="check3">Android</label>
            <div class="collapse {% if app.link_Android %}show{%endif%}" id="link3">
              <input type="url" class="col-xs-12" name="link_Android" placeholder="ダウンロードリンク" value="{% if app.link_Android  != None %}{{app.link_Android}}{%endif%}">
            </div>
          </div>
          <div>
            <input class="form-check-input" type="checkbox" id="check4" name="check4" data-toggle="collapse"
              data-target="#link4" href="#link4" aria-expanded="false" aria-controls="link4" {% if app.link_iOS%}checked{%endif%}>
            <label class="form-check-label" for="check4">iOS</label>
            <div class="collapse {% if app.link_iOS%}show{%endif%}" id="link4">
              <input type="url" class="col-xs-12" name="link_iOS" placeholder="ダウンロードリンク" value="{% if app.link_iOS  != None %}{{app.link_iOS}}{%endif%}">
            </div>
          </div>

        </div>
      </div>

      <div class="col-12 p-4 text-center text-break">
        <a class="px-3"><button type="submit" class="btn btn-primary">変更申請</button></a>
        <a class="px-3"><a href="{% url 'mypage:delete_application' app.id %}" class="btn btn-danger">削除申請</a></a>
      </div>
    </form>
  </div>
</main>
{% endblock main %}