backend/contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'
urlpatterns = [
    path('about/', views.AboutView.as_view(), name='about'),
]

backend/developers/urls.py
from django.urls import path

from . import views

app_name = 'developers'
urlpatterns = [
    path('', views.DevelopersView.as_view(), name='home'),
    path('detail/<uuid:pk>/', views.DevelopersDetailView.as_view(), name='detail'),
]

backend/home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('search', views.SearchView.as_view(), name='search'),
    path('getkeywords', views.keywords_api, name='keywords_api')
]

backend/mypage/urls.py
from django.urls import path

from . import views

app_name = 'mypage'
urlpatterns = [
    path('<uuid:pk>/', views.MypageHomeView.as_view(), name='home'),
    path('profile/update/', views.ProfileUpdateView.as_view(), name='profile_update'),
    path('developments/new/', views.DevelopmentNewView.as_view(), name='developments_new'),
    path('developments/update/<int:pk>/', views.DevelopmentUpdateView.as_view(), name='developments_update'),
    path('developments/delete/<int:pk>/', views.DevelopmentDeleteView.as_view(), name='developments_delete'),
    path('developments/detail/<int:pk>/', views.DevelopmentDetailView.as_view(), name='developments_detail'),
    # path('new_application/', views.NewApplication.as_view(), name='new_application'),
    # path('update_application/<int:id>', views.UpdateApplication.as_view(), name='update_application'),
    # path('delete_application/<int:id>', views.DeleteApplication, name='delete_application'),
    # path('game_detail/<int:pk>/', views.MypageGameDetailView.as_view(), name='game_detail')
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .common_settings import *

urlpatterns = [
    path('misw/admin/', admin.site.urls),
    path('', include('social_django.urls')),
    path('', include('backend.oauth.urls')),
    path('', include('backend.home.urls')),
    path('developers/', include('backend.developers.urls')),
    path('', include('backend.developments.urls')),
    path('', include('backend.contact.urls')),
    path('mypage/', include('backend.mypage.urls')),
    path('manage/', include('backend.manage.urls')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>{% block title %}{% endblock %}</title>

  <!-- BootstrapのCSS読み込み -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <link href="{% static 'css/footer.css' %}" rel="stylesheet">

  <!-- jQuery読み込み -->
  <link href="{% static 'vendor/jquery/jquery-ui.css' %}" rel="stylesheet">
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/jquery/jquery-ui.js' %}"></script>

  <!-- BootstrapのJS読み込み -->
  <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>

  {% block head %}{% endblock %}
</head>

<body>
{% block headerupper %}{% endblock %}

<header>
  {% if user.is_authenticated %}
    <div class="container-fluid p-0">
      <nav class="navbar navbar-expand navbar-light" style="background-color:rgb(195, 215, 252)">
        <ul class="nav nav-tabs mr-auto">
          <li class="float-left">
            <a href="{% url 'home:home' %}" class="nav-item navbar-brand">みすミュージアム</a>
            <a href="{% url 'developers:home' %}"
               class="nav-item navbar-link text-secondary d-none d-sm-inline-block">開発者一覧&nbsp;</a>
            <a href="{% url 'contact:about' %}"
               class="nav-item navbar-link text-secondary d-none d-sm-inline-block">このサイトについて</a>
          </li>

        </ul>

        <ul class="nav nav-tabs">
          <li class="nav-item nav-link d-none d-sm-inline-block">
            <a href="{% url 'mypage:developments_new' %}">
              <button type="button" class="btn btn-primary">新規申請</button>
            </a>
          </li>
          <li class="nav-item dropdown pr-2">
            <button class="dropdown-toggle p-2" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
              {% if user.image %}
                <img src="{{ user.image.url }}" class="rounded-circle" width="32" height="32">
              {% else %}
                <img src="{% static 'icons/profile.svg' %}" class="rounded-circle" width="32" height="32">
              {% endif %}

            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
              <div class="d-sm-none text-center py-2">
                <a href="{% url 'mypage:developments_new' %}">
                  <button type="button" class="btn btn-primary">新規申請</button>
                </a>
              </div>
              <div class="py-2">
                <a class="dropdown-item" href="{% url 'mypage:home' user.pk %}">マイページトップへ</a>
              </div>
              <div class="py-2">
                <a class="dropdown-item" href="{% url 'mypage:profile_update' %}">プロフィール変更</a>
              </div>
              <hr>
              <div class="py-2">
                <a class="dropdown-item" href="{% url 'developers:home' %}">開発者一覧</a>
              </div>
              <div class="py-2">
                <a class="dropdown-item" href="{% url 'contact:about' %}">このサイトについて</a>
              </div>
              <hr>
              <div class="py-2">
                <a class="dropdown-item" href="/logout/">ログアウト</a>
              </div>
              <div role="separator" class="divider"></div>
            </div>
          </li>
        </ul>
      </nav>
    </div>
  {% else %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'home:home' %}">みすミュージアム</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
              aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'developers:home' %}">開発者一覧</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'contact:about' %}">このサイトについて</a>
          </li>
        </ul>

        <ul class="nav nav-tabs pull-right">
          <li class="nav-item">
            <a href="/login/auth0">
              <button type="button" class="btn btn-primary">ログイン</button>
            </a>
          </li>
        </ul>

      </div>
    </nav>
  {% endif %}
</header>

{% block main %}{% endblock %}

<footer id="footer" role="contentinfo"
        class="site-footer main-footer footer-bottom-vertical site-footer-inverted main-footer-inverted">
  <div class="foot-container">
    <div class="footer-widgets">
      <div class="footer--widgets widget-area widgets--columned-layout widgets--columns-3" role="complementary">
        <div id="custom_html-2" class="widget_text widget widget_custom_html">
          <div class="textwidget custom-html-widget">
            <div id="share_field">
              <p style="text-align: center; color: #333; font-weight: bold; font-size: 22px; letter-spacing: 1px;">
                SHARE
              </p>
              <a href="https://www.facebook.com/sharer/sharer.php?u=https://misw.jp" target="_blank"
                 rel="noopener noreferrer">
                <img class="snsbutton" src="{% static 'icons/f-ogo_RGB_HEX-100.png' %}" width="30" height="auto">
              </a>
              <a href="http://twitter.com/share?url=https://misw.jp&amp;text=デジタル創作サークル「MIS.W」&amp;related=misw_info"
                 target="_blank" rel="noopener noreferrer">
                <img class="snsbutton" src="{% static 'icons/Twitter_Social_Icon_Square_Color.png' %}" width="30"
                     height="auto">
              </a>
              <a href="https://social-plugins.line.me/lineit/share?url=https://misw.jp" target="_blank"
                 rel="noopener noreferrer">
                <img class="snsbutton" src="{% static 'icons/LINE_SOCIAL_Square_typeA.png' %}" width="30"
                     height="auto">
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <hr>
  </div>
  <div class="footer-bottom">
    <div class="container">
      <div class="footer-bottom-content">
        <div>
          <div>
            <span style="color: #ffffff; ">© 2018-2021 MIS.W</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>
</body>

</html>