backend/developers/urls.py
from django.urls import path

from . import views

app_name = 'developers'
urlpatterns = [
    path('', views.DevelopersView.as_view(), name='home'),
    path('detail/<uuid:pk>/', views.DevelopersDetailView.as_view(), name='detail'),
]

backend/developments/urls.py
from django.urls import path

from . import views

app_name = 'developments'
urlpatterns = [
    path('detail/<int:pk>/', views.DevelopmentDetailView.as_view(), name='detail'),
]

config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

from .common_settings import *

urlpatterns = [
    path('misw/admin/', admin.site.urls),
    path('', include('social_django.urls')),
    path('', include('backend.oauth.urls')),
    path('', include('backend.home.urls')),
    path('developers/', include('backend.developers.urls')),
    path('', include('backend.developments.urls')),
    path('', include('backend.contact.urls')),
    path('mypage/', include('backend.mypage.urls')),
    path('manage/', include('backend.manage.urls')),
]

urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

backend/developers/views.py
from django.views import generic

from backend.developments.models import Development
from backend.users.models import User


class DevelopersView(generic.TemplateView):
    template_name = 'developers/index.html'

    def get(self, *args, **kwargs):
        context = {
            'developers': User.objects.filter(is_superuser=False).order_by('generation', 'username')
        }

        return self.render_to_response(context)


class DevelopersDetailView(generic.TemplateView):
    template_name = 'developers/detail.html'
    model = User

    def get(self, *args, **kwargs):
        context = {
            'developer': self.model.objects.get(pk=self.kwargs['pk']),
            'developments': Development.objects.filter(developer_id=self.kwargs['pk'], status=1).order_by('updated_at')
        }

        return self.render_to_response(context)

templates/developers/detail.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  MISW Museum | 開発者詳細
{% endblock title %}


{% block main %}
  <main role="main">
    <section class="jumbotron text-center">
      <div class="container">
        <div class="row align-items-center mx-auto justify-content-center">
          <div class="col-12 col-md-4 text-center">
            <!-- col-12 col-md-4 -->
            <!-- col-4 col-auto-->
            {% if developer.image %}
              <img class="rounded-circle" src="{{ developer.image.url }}" width="200" height="200">
            {% else %}
              <img class="rounded-circle" src="{% static 'icons/profile.svg' %}" width="200" height="200">
            {% endif %}
          </div>
          <div class="d-md-none p-4"></div>
          <div class="col-12 col-md-8 text-left">
            <!-- col-12 col-md-8 -->
            <!-- col-8 col-auto-->
            <div style="overflow-wrap: break-word; word-wrap: break-word;">
              <div class="row p-2">
                <span class="col-6 col-md-5">ハンドルネーム: </span>
                <span class="col-6 col-md-5">{{ developer.first_name }}</span>
              </div>
              <div class="row p-2">
                <span class="col-6 col-md-5">代: </span>
                {% if developer.generation %}
                  <span class="col-6 col-md-5">{{ developer.generation }}</span>
                {% else %}
                  <span class="col-6 col-md-5">-</span>
                {% endif %}
              </div>
              <div class="row p-2">
                <span class="col-6 col-md-5">ひとこと: </span>
                <span class="col-6 col-md-5">
                <p>{{ developer.description }}</p>
              </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <div class="container">
      {% for development in developments %}
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            {% if development.top_image %}
              <img class="card-img-top" style="height: 200px; width: 100%; display: block;"
                   src="{{ development.top_image.url }}" data-holder-rendered="true">
            {% else %}
              <img class="card-img-top" style="height: 200px; width: 100%; display: block;"
                   src="{% static 'icons/noimage.png' %}" data-holder-rendered="true">
            {% endif %}
            <div class="card-body">
              <p class="card-text">
                <span style="font-size: large; ">{{ development.title }}</span>
              </p>
              <p>作成者： {{ development.user.first_name }}</p>
              <div class="d-flex justify-content-between align-items-center">

                <a href="{% url 'developments:detail' development.pk %}">詳しく見る</a>

              </div>
            </div>
          </div>
        </div>
      {% endfor %}
    </div>
  </main>
{% endblock main %}

templates/developers/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
  MISW Museum | 開発者一覧
{% endblock title %}

{% block main %}
  <main role="main">
    <section class="jumbotron-heading2 text-center px-5 py-5">
      <div>
        <h2>開発者一覧</h2>
      </div>
    </section>

    <div>
      <div class="container">
        <div class="row">
          {% for developer in developers %}
            <div class="col-md-4">
              <div class="card mb-4 shadow-sm">
                {% if developer.image %}
                  <img class="card-img-top" style="height: 300px; width: 100%; display: block;"
                       src="{{ developer.image.url }}" data-holder-rendered="true">
                {% else %}
                  <img class="card-img-top" style="height: 300px; width: 100%; display: block;"
                       src="{% static 'icons/profile.svg' %}" data-holder-rendered="true">
                {% endif %}
                <div class="card-body">
                  <p class="card-text">
                    <font size="5">{{ developer.first_name }}</font>
                  </p>
                  {% if developer.generation %}
                    <p>{{ developer.generation }}代</p>
                  {% else %}
                    <p>-代</p>
                  {% endif %}
                  <div class="d-flex justify-content-between align-items-center">
                    <a href="{% url 'developers:detail' developer.pk %}">詳しく見る</a>
                  </div>
                </div>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </main>
{% endblock main %}